#!/bin/sh

mdfile=""

if [[ $1 == *".md"* ]]; then
	mdfile=$1
elif [[ $1 == *. ]]; then
	mdfile="${1}md"
else
	mdfile="${1}.md"
fi

if [[ ! -f $mdfile ]]; then
	echo "File $mdfile doesn't exist. You twat."
	exit 1
fi

outfile="${mdfile::-2}pdf"

#pandoc --toc --pdf-engine=xelatex -V CJKmainfont="Source Han Sans CN" --from markdown+simple_tables --from markdown+implicit_figures $mdfile -o $outfile --template "/home/v/bin/md/tex/lab.latex"
pandoc --toc --from markdown+simple_tables --from markdown+implicit_figures $mdfile -o $outfile --template "/home/v/bin/md/tex/lab.latex"
