#!/bin/bash

wd=$PWD
arg1=$1

filetowatch=""
outputformat=""
template=""
templatedir=""

function usage {
	echo -e "\nUsage: mdlive [-o outputformat] [-t template] [-f filename]"
	echo -e "\nwhere:"
	echo -e "  outputformat = {pdf, html}"
	echo -e "  template = {default, essay, syllabus, ... look in ~/bin/md/ for more}"
	echo -e "  filename = the file you want to watch (if none, watch all .md files in directory)\n"
}

while getopts "ho:t:f:" opt; do
	case $opt in 
		h) 
			usage
			;;
		o)
			outputformat="$OPTARG"
			;;
		t)
			template="$OPTARG"
			;;
		f)
			filetowatch=$OPTARG
			;;
		\?)	
			echo -e "\nYou twat."
			usage
			;;
	esac
done
shift $((OPTIND -1))

if [[ $outputformat == *"pdf"* ]]; then
	outformat="pdf"
	templatedir="~/bin/md/tex/"
elif [[ $outputformat == *"html"* ]]; then
	outformat="html"
	templatedir="~/bin/css/"
else
	echo -e "\nInvalid output format specified."
	usage
	exit 1
fi

if [ -z $filetowatch ]; then
	echo "No specified file to watch. Watching all .md files in directory."
fi

inotifywait -m -e modify --format '%f' ./ |
	while read file; do
		if [[ "$infile" =~ .md ]]; then

#			if [[ "$outformat" == *"html"* ]]; then
#				htmlfile="${file::-2}html"
#
#				pandoc --mathjax --toc --from markdown+latex_macros --from markdown+pipe_tables --from markdown+raw_tex --number-sections $file -s -c style.css -o $htmlfile
#
#				title=`sed "2q;d" $file | cut -d'"' -f 2 | tr -d "0123456789"`
#				chapter=`sed '3q;d' $file | cut -d'"' -f 2`
#				part=`sed '4q;d' $file | cut -d'"' -f 2`
#
#				webdir="../content/$part/"
#				webfpath="${webdir}${htmlfile}"
#
#				cp $htmlfile "${webdir}${htmlfile}"
#
#				echo "---" | cat - $webfpath > tmp && mv tmp $webfpath
#				echo "weight: $chapter" | cat - $webfpath > tmp && mv tmp $webfpath
#				echo "title: '$title'" | cat - $webfpath > tmp && mv tmp $webfpath
#				echo "---" | cat - $webfpath > tmp && mv tmp $webfpath

			outfile="${infile::-2}pdf"
			pandoc --toc $infile -o $outfile --template "${templatedir}${template}.latex"

		fi
	done
