#!/bin/bash

mdfile=""

if [[ $1 == *".md"* ]]; then
	mdfile=$1
elif [[ $1 == *. ]]; then
	mdfile="${1}md"
else
	mdfile="${1}.md"
fi

if [[ ! -f $mdfile ]]; then
	echo "File $mdfile doesn't exist. You twat."
	exit 1
fi

outfile="${mdfile::-2}pdf"

mode=$2
extensions=""
template=""

case $mode in
	-g|--grade)
	extensions="--from markdown+pipe_tables"
	template="gradecomments.latex"
	shift
	shift
	;;
	-l|--labmanual)
	extensions="--toc --from markdown+pipe_tables"
	template="labmanual.latex"
	shift
	shift
	;;
esac

pandoc $extensions $mdfile -o $outfile --template "${HOME}/bin/latex/$template"

#pandoc --toc --from markdown+pipe_tables $mdfile -o $outfile --template "/home/v/bin/md/tex/gradecomments.latex"
