#!/bin/bash

templates=( \
	"pl|plain (default)"\ 
	"gr|gradecomments"\
	"la|labmanual"\
	"sy|syllabus"\ 
	)

options=(\
	"-z 	render 中文 (use xelatex, set CJKfont, etc)"\
	"-c	add table of contents"\
	"-x	save .tex file (create ./tex/ directory)"\
	)

usage_message() {
	echo -e "\nUsage: mdpdf <mdfile> [-t template] [options]\n"
	echo "templates:"
	for i in "${templates[@]}"; do
		echo "      $i"
	done
	echo -e "\noptions:"
	for i in "${options[@]}"; do
		echo "      $i"
	done
	echo ""
	exit
}

if [ "$#" == 0 ] ; then usage_message ; fi

infile=$1
mdfile=""

if [[ $infile == *".md"* ]]; then
	mdfile=$infile
elif [[ $infile == *. ]]; then
	mdfile="${infile}md"
else
	mdfile="${infile}.md"
fi

if [[ ! -f $mdfile ]]; then
	echo "File $mdfile doesn't exist, twat"
	exit 1
fi

shift

pdffile="${mdfile::-2}pdf"
texfile="${mdfile::-2}tex"
template=""
chinese=0
extensions=""
convert="${mdfile} -o ${pdffile}"

while getopts "h:t:zcx" opt; do
	case ${opt} in 
		h)
			usage_message
			;;
		t)
			template=$OPTARG
			;;
		z)
			chinese=1
			;;
		c)
			extensions+=" --toc"
			;;
		x)
			mkdir -p ./tex/
			convert="${mdfile} -o ./tex/${texfile}"
			;;
		\?)	
			echo -e "\nYou twat."
			usage
			;;
	esac
done

templatesrc=""

case $template in
	pl|plain)
		extensions+=" --from markdown+pipe_tables"
		templatesrc="plain.latex"
		shift
		shift
		;;
	gr|gradecomments)
		extensions+=" --from markdown+pipe_tables"
		templatesrc="gradecomments.latex"
		shift
		shift
		;;
	la|labmanual)
		extensions+=" --toc --from markdown+pipe_tables"
		templatesrc="labmanual.latex"
		shift
		shift
		;;
	sy|syllabus)
		extensions+=" --from markdown+pipe_tables"
		templatesrc="syllabus.latex"
		shift
		shift
		;;
	*)
		extensions+=" --from markdown+pipe_tables"
		templatesrc="plain.latex"
		shift
		shift
		;;
esac

if [[ $chinese -eq 1 ]]; then
	echo "Converting ${mdfile}"
	echo "Template: ${templatesrc}"
	echo "(with 中文)"
	pandoc --pdf-engine=xelatex -V CJKmainfont='Source Han Sans CN' \
		$extensions $convert \
		--template ${HOME}/bin/latex/$templatesrc
else
	echo "Converting ${mdfile}"
	echo "Template: ${templatesrc}"
	pandoc $extensions $convert --template ${HOME}/bin/latex/$templatesrc
fi

echo "Done."
